"""
DeltaNeutralAaveV3UniV3WETHUSDCBase Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import DeltaNeutralAaveV3UniV3WETHUSDCBaseStrategy
except ImportError:
    from strategy import DeltaNeutralAaveV3UniV3WETHUSDCBaseStrategy

__all__ = [
    "DeltaNeutralAaveV3UniV3WETHUSDCBaseStrategy",
]
